CREATE TABLE USERS (
			ID INT NOT NULL,
			FIRSTNAME VARCHAR(40) NOT NULL,
			LASTNAME VARCHAR(40) NOT NULL,
			EMAIL VARCHAR(40) NOT NULL,
			PHONENUMBER VARCHAR(10) NOT NULL,
			BIRTHDATE DATE NOT NULL,
			USERNAME VARCHAR(40) NOT NULL,
			PASSWORD VARCHAR(40) NOT NULL,
			PRIMARY KEY(ID)
);